### ISSUE TITLE
Tab Bar Hide is reset each time compare is done

### ISSUE THREAD

**Issue by HolterPhylo** [pnedev/comparePlus#320]
Using npp++ v8.4.4 and comparePlus v.1.0.0

Like the title says:  Each time I use compare, Settings->Preferences->Tab Bar->Hide is reset and the tabs reappear (I prefer to always use the Document list with no tab visible)

**Comment by Yaron10** [comment]
@HolterPhylo,

I can not reproduce that.
@pnedev will probably reply next week.

**Comment by Yaron10** [comment]
@HolterPhylo,

I suppose you use "Set as First to Compare". It's expected that ComparePlus should display the TabBar in that case.
If you use "Compare" (default: compare current and previous tabs), the TabBar will not be displayed.

**Comment by HolterPhylo** [comment]
![Screenshot - 9_16_2022 , 8_58_14 PM](https://user-images.githubusercontent.com/3037251/190834307-40aab632-1871-4f4f-b9b6-d6acf1ba195a.png)

If I do just "Compare" as you suggest: Tabs do not open
If I do "Set as First" and then "Compare": Tabs open and do not restore preferences (even after "Clear active compare")
Small video to demonstrate:
https://user-images.githubusercontent.com/3037251/190834661-ec9d5170-e39e-4b3d-8d47-e9205a94520c.mp4

**Comment by Yaron10** [comment]
@HolterPhylo,

You're right.

As I wrote in my previous post:
Your preference should indeed be restored at this stage.
That is: after "Set as First, Compare" or "Set as First, Clear Compare".

**Comment by pnedev** [comment]
Hello @HolterPhylo, 
Hello @Yaron10, 

The issue is fixed:
- Win 32-bit binary is at https://ci.appveyor.com/project/pnedev/compareplus/builds/44814654/job/qvhq6aqty5me8phe/artifacts
- Win 64-bit binary is at https://ci.appveyor.com/project/pnedev/compareplus/builds/44814654/job/w0hnve0oyrlin0a0/artifacts
- ARM64 binary is at https://ci.appveyor.com/project/pnedev/compareplus/builds/44814654/job/dmymc92avp4mpu8b/artifacts

Thank you for the support Yaron :+1: 

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for the quick fix. I appreciate it. 👍 

BR

**Comment by HolterPhylo** [comment]
@pnedev,

Thanks, tested and this indeed corrected and even improved ComparePlus (no more tabs appearing)
Great!
