### ISSUE TITLE
Visible Lines after Clearing "Selection Compare"

### ISSUE THREAD

**Issue by Yaron10** [pnedev/comparePlus#342]
Hello Pavel,

Could you please Compare Selections in [these files](https://github.com/pnedev/comparePlus/files/10300425/Stylers.zip)?
Select lines 936-941 in both files.
Compare Selections.
Clear Compare.

Result:
The top/first lines are visible _in the active file_ (the caret is in the expected position though).

Whenever you find some free time.
Thank you very much.

BR

**Comment by pnedev** [comment]
Hello Yaron,

I'll look into it, sure.
Thank you.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you for that too.

BR

**Comment by pnedev** [comment]
Hello Yaron,

The problem should be fixed in this build: https://ci.appveyor.com/project/pnedev/compareplus/builds/45790174
Could you please confirm?
Thank you very much!
There is still slight problem with that but I assume that couldn't be easily fixed - when you have other opened files and after the selection compare you activate one of the other files and use `Clear all compares`. Let's leave that as a known issue.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

👍 
Excellent!
Thank you for the quick fix. Much appreciated.

> when you have other opened files and after the selection compare you activate one...

I couldn't reproduce it with my files and selections above. :)
Anyway, "Let's leave that as a known issue.".

BR
