### ISSUE TITLE
Unexpected behavior when Ignore whitespace selected

### ISSUE THREAD

**Issue by jeesusonherraturku** [pnedev/comparePlus#345]
Thank you for this very useful plugin.  

I tested whether I can get same results using Winmerge and comparePlus plugin. 

When Ignore whitespace is ON: Below is an image of Winmerge (one line). The functionality is what I expect. The red part shows that one word is different. comparePlus plugin however ignores the whole line and does not show any difference. (The language is in Finnish). 

![winmerge_ignore_whitespaces](https://user-images.githubusercontent.com/117400574/212398344-242e0668-62de-4f50-abc9-adfef54c129c.jpg)

In Winmerge there are two options for Ignoring  whitespace, "Ignore All" and "Ignore changes". I have "Ignore changes" selected, maybe this is why it works differently. 

I would suppose that many people would want to see the important difference as illustrated in the picture. In my case I cannot set Ignore whitespace completely OFF , since it will fill my screen with too many lines that I dont want to see ( I have also "show only differences" selected).

I may have other questions but I will open a separate issue if necessary. 

Thank you.

**Comment by jeesusonherraturku** [comment]
I tested that if I select "Ignore All" in Winmerge, then the behavior seems to be similar than in comparePlus plugin. 

Perhaps "Ignore changes" functionality comes to comparePlus plugin also, so that we can see important differences as in my example.  If I understood correctly it is otherwise similar to "Ignore all". It appears to be quite simple functionality described here

https://manual.winmerge.org/en/Compare_files.html#CompareFiles_linediff-highlight

**Comment by pnedev** [comment]
Hello @jeesusonherraturku ,

You are right, when 'Ignore Spaces' is enabled in ComparePlus it behaves as if they are not there so `j otka` matches `jotka` in your example. This might seem awkward to the user, I agree. I'll examine this a bit and see if I should change the behavior or add additional 'Ignore changed spaces' option (the current is 'Ignore all spaces').

**Comment by pnedev** [comment]
Hello @jeesusonherraturku , All,

Please try this CP development build ([win32](https://ci.appveyor.com/api/buildjobs/f02me63ucjsc52ry/artifacts/ComparePlus.dll) or [win64](https://ci.appveyor.com/api/buildjobs/pagk64r3r742v4nm/artifacts/ComparePlus.dll)) and tell me what you think. It has implementation of "Ignore All Spaces" (the current behavior that removes all spaces) and the new option "Ignore Changed Spaces" that only ignores the spaces in certain place that have different type/size.

You could try comparing these lines (use Copy/Paste):
file 1: `this is a test   line  `
file 2: ` this is atest line`
Try the two options but have in mind that "Ignore All Spaces" has higher priority and if both are checked (enabled) the behavior will be like "Ignore All Spaces".

I would appreciate your opinion on this particular case:
Shall "Ignore Changed Spaces" totally ignore the spaces in the beginning and the end of the lines so only for the beginning and the end of the lines to behave like "Ignore All Spaces"?
For all other places the space is kept as a words delimiter and is not ignored totally - it should be present in order to keep the words separate but its format and size doesn't matter.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Thank you very much for another excellent improvement. Much appreciated. 👍 

> Try the two options but have in mind that "Ignore All Spaces" has higher priority and if both are checked (enabled) the behavior will be like "Ignore All Spaces".

Wouldn't it be better if only one option could be checked at any given time? - I think this is the expected behavior, and it would also be much clearer.
(When the user checks one option, programmatically uncheck/disable the other one).

 > Shall "Ignore Changed Spaces" totally ignore the spaces in the beginning and the end of the lines...

If I understand correctly the request here and its usefulness in real-life, a _space between non-space characters_ might fundamentally change the meaning of the text and create two completely different words.
This, apparently, is irrelevant to leading/trailing spaces. 

Let's see what the others think.

BR

***

Hello @jeesusonherraturku,

Thank you for opening this issue.

**Comment by jeesusonherraturku** [comment]
Hello, 

Thank you for the update!

I downloaded the update and was able to do testing. It seems to work quite well most of the time. Occasionally Notepad++ hangs if I put spaces or tabs at the of line (closes automatically after about 5 seconds). It seems to occur if only other line has spaces/tabs at the end of line, but the compared line does not. I was able to take screenshot of one comparison that crashed. I dont know if its only my system. 

![New Project](https://user-images.githubusercontent.com/117400574/213518119-a5b96395-e47e-4f27-97a6-0211efc1ae40.jpg)


For the other thing: 

Personally, I would prefer ignoring all spaces/tabs at the beginning and end of lines when "Ignore changed spaces" .  

For better illustration I took picture of Winmerge to show how it works currently when "Ignore changes". It ignores all spaces/tabs at the end in all cases. But for the beginning it works differently. If either line does not have any spaces/tabs at the beginning it will not ignore them, but if both lines have at least one space then it will ignore. My use case(scanned documents) often leaves excessive spaces/tabs at the end, so Im happy that they are ignored, while showing if a whole word has changed meaning. I dont know why for the beginning of lines it works differently in Winmerge. I would prefer at least for the end of lines ignoring all spaces/tabs (otherwise it is not so useful)

(In the picture the spaces and tabs are marked show you can see them). 

![New Project (1)](https://user-images.githubusercontent.com/117400574/213523234-7bcc7685-3103-4ee0-85ee-c189b2fe795b.jpg)


Hopefully I didnt make errors in my explanation. Thank you for your hard work.

**Comment by Yaron10** [comment]
I can reproduce the crash with previous ComparePlus builds as well.

**STR:**
Uncheck `Ignore Spaces`.
Compare [these files](https://github.com/pnedev/comparePlus/files/10460371/TestSpaces.zip).

**Result:**
NPP crashes.

**Comment by pnedev** [comment]
Hello guys,

Thank you both for the feedback.

I see that both of you prefer to totally ignore spaces in the beginning and at the end of the line when "Ignore Changed Spaces" is enabled. I also think that would be better.

Unfortunately I couldn't reproduce the crash you have observed under Wine on Linux. I'll try on native Win11 some time later, thanks for letting me know.

Yaron,

Regarding 

>Wouldn't it be better if only one option could be checked at any given time? - I think this is the expected behavior, and it would also be much clearer.
>(When the user checks one option, programmatically uncheck/disable the other one).

I see your point but such implementation is not very optimal and straightforward.
It doesn't seem very handy for the user if the two options are mutually exclusive and disabling each other because for example one might want to use mainly "Ignore changed" and from time to time to enable "Ignore all" on top of it. Now if we have "Ignore changed" enabled then "All" will be disabled and the user would have to go to NPP plugin twice to first disable "Changed" and then to enable "All". The same scenario is valid also if enabling temporarily "All" leads to automatic disabling of "Changed".
So maybe "All" (as it is the more strict limitation and thus has the higher effect) could make "Changed" inactive but not the other way around.
My personal preference would be to leave them as they are because that way they are more easily changeable and in my opinion are not ambiguous.
If you can think of a good way to make your suggestion more clear and easy for the user I would certainly consider it.

Thanks again for the discussion, much appreciated.

**Comment by Yaron10** [comment]
Hello Pavel,

> I see that both of you prefer to totally ignore spaces...
...
I'll try on native Win11 some time later...

👍 

***

**Concept:**
"Ignore Changed Spaces" is actually "Ignore Changed Spaces **Only**".
Aren't the two commands "All" and "Only" contradicting?

_A side note:_
See how NPP implements "View -> Show Symbol -> Show White Space and Tab" and "View -> Show Symbol -> Show End of Line".
Checking one command, automatically unchecks the other.
IMO, that behavior is wrong in that case: the two commands are not contradicting whatsoever.
(The third command "Show All Characters" probably made the coder implement it that way). 

**Practically:**
I see your point. But...
Yesterday, testing this new feature and trying _either All or Only_ - I found the necessity to check one and uncheck the other (each time I wanted to switch between the modes) slightly inconvenient and unexpected.  

> My personal preference would be to leave them as they are because that way they are more easily changeable and in my opinion are not ambiguous.

You are the maestro! :)

Thanks again for your time and work. I do appreciate it.

BR

**Comment by pnedev** [comment]
Hello again guys,

I managed to reproduce the NPP crash on Win11. It doesn't appear to be related to the spaces. I'll find the reason and fix it.

Yaron,

>Checking one command, automatically unchecks the other.

I like that solution and implement it that way. Thank you 👍 

BR

**Comment by Yaron10** [comment]
Hello Pavel,

👍 
Great. I appreciate it.

BR

**Comment by pnedev** [comment]
Hello guys,

Mutually exclusive 'Ignore Spaces....' options behavior is implemented and also the line start/end spaces are now always ignored when one of them is active.
Please try this development build and tell me what you think: [win32](https://ci.appveyor.com/api/buildjobs/tp9rli0j7kbe33k0/artifacts/ComparePlus.dll), [win64](https://ci.appveyor.com/api/buildjobs/4d4ojg07s0t1cuau/artifacts/ComparePlus.dll).

I'll let you know when I fix the NPP crash issue. Meanwhile just don't compare files that have a single line.
Thanks!

BR

**Comment by Yaron10** [comment]
Hello Pavel,

👍 
Brilliant!
Thank you for the major refactoring. Much appreciated.

BR

**Comment by jeesusonherraturku** [comment]
Hi, 

Thank you. 

Based on my testing it seems to work properly now. 

Only thing I observed was that when you change between 'compare all' and 'compare changes' you need to press Compare button, it does not work automatically. Maybe its intentional.

**Comment by pnedev** [comment]
> Maybe its intentional.

Yes, that is intentional.
ComparePlus reads its compare options just before you start the compare and keeps them unchanged during Auto-updating process when you change the contents of the compared files. It is done so you don't compromise your current compare if you want to change your options and compare other files.
Changing the compare options will require manually re-comparing the files.

Thanks.
BR

**Comment by pnedev** [comment]
Hello guys,

The NPP crash when single-line files are compared is fixed, this is the development build: [win32](https://ci.appveyor.com/api/buildjobs/2ch0g5jqj85376rg/artifacts/ComparePlus.dll), [win64](https://ci.appveyor.com/api/buildjobs/li154p78kusimrs9/artifacts/ComparePlus.dll).

Thank you both for testing and reporting 👍 
BR

**Comment by Yaron10** [comment]
Hello Pavel,

:+1: 
Great!
Thanks again for your time and work.

BR
