### ISSUE TITLE
Comparing two file says "match" when they are not

### ISSUE THREAD

**Issue by szkkam** [pnedev/comparePlus#348]
I had two files that I know ware slightly different. Compared them with plugin to find that differences but was surprised with "files match" output. Then copied lines that ware different to new empty files, compared again and still "match". Is it expected behavior or a bug? 

File 1 content:
`TESTFILE02;PoweredOff;4;4;0;0;100`

File 2 content:
`TESTFILE02;PoweredOff;4;4;100;0;0`

Notepad++ ver v8.4.2 32b
ComparePlus v1.1

**Comment by pnedev** [comment]
Hello,

Comparing the files contents you provided works as expected on my side, correctly showing the differences.
I am using the current development version of ComparePlus but I don't remember making changes to the compare algorithm since v1.1.
Could you get [this Win32-bit](https://ci.appveyor.com/api/buildjobs/03d2l0pt7jpr95e2/artifacts/ComparePlus.dll) development binary and try again on your side?
You might need to update your Notepad++ version to 8.4.9 as well if you encounter compatibility issues because there had been quite a few major N++ updates recently affecting plugins operation.

BR

**Comment by szkkam** [comment]
Replacing dll didn't change anything. After upgrading N++ to newest ver 8.4.9 both dll's work fine. This N++ installation was managed by SCCM so it could be updated recently without me even noticing it but I'm not sure because it was working fine like monthago. It could be broken that way or it was problem with that specific version. I'm closing issue anyway.

I was checking those files a bit more and Compare was ignoring differences as long as length of string or substring was the same:

Match:
```
TESTFILE02;PoweredOff;4;4;0;0;100
TESTFILE02;PoweredOff;4;5;100;0;0
```

Not match:
```
TESTFILE02;PoweredOff;4;4;0;0;100
TESTFILE02;PoweredOff;4;4;1000;0;0
```
