### ISSUE TITLE
ComparePlus crash in combination with NppTextFX2

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [pnedev/comparePlus#361]
Hello over there,

with NPP 8.5.4 (64bit) I wanted to switch from Compare to ComparePlus (CP),
but CP even crashed on my really simple test comparison:

older.txt:
```
Older file
this text will be unchanged
this line will be deleted in newer file
this line will be changed in newer file
```

newer.txt:
```
Newer file
this text will be unchanged
this line will be tschanged in newer file
```

After pressing \<Ctrl\>\<Alt\>\<C\> compare results will be shown immediately, everything seems to be normal.
Except that there is no cursor action anymore ... and about five seconds later NPP crashes.

Have a bunch of plugins installed, but managed to nail it down to NppTextFX2:
if there's just CP and NppTextFX2 installed, CP crashes.
Without NppTextFX2, CP even works with all of my other plugins installed.
Probably needless to say that I haven't had any problems with NppTextFX2 so far.

Anything I can do about this?

Thx a lot in advance!

Ah, Debug info:
```
Notepad++ v8.5.4   (64-bit)
Build time : Jun 17 2023 - 20:42:45
Path : D:\Programme\Notepad++\notepad++.exe
Command Line : "D:\Users\Me\Desktop\older.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.3208
Current ANSI codepage : 1252
Plugins : 
    AutoCodepage (1.2.6)
    BigFiles (0.1.3)
    BracketsCheck (1.2.2)
    ColumnTools (1.4.5.1)
    ComparePlus (1.1)
    CSVLint (0.4.6.5)
    CsvQuery (1.2.9)
    DSpellCheck (1.5)
    HexEditor (0.9.12)
    HTMLTag (1.3.7)
    HugeFiles (0.4.1)
    mimeTools (2.9)
    NotepadStarterPlugin (2.3.3)
    nppAutoDetectIndent (2.3)
    nppConverter (4.5)
    NppExport (0.4)
    NppFTP (0.29.12)
    NppQrCode64 (0.0.0.1)
    NppSaveAsAdmin (1.0.211)
    NppTextFX (1.4.1)
    NppTextViz (0.4.2)
    NppToolBucket (1.10.6622.41516)
    Remove Duplicate Lines (1.3)
    XMLTools (3.1.1.13)
```

**Comment by MagpieFourtyTwo** [comment]
Ah, the predecessor "ComparePlugin", I had till then (and which I used right now again), works like a charm.

And perhaps s/one can say s/th about this strange behavior (which is the same in ComparePlugin and ComparePlus):
If I compare two files, the current line background gets a different color, is in fact pretty dark (in Plus even darker).
But if I close one of the two files, the current line background will be black ... so there is black text on black background now)
This can only be changed by "pseudo changing" ``Settings`` --> ``Style Configurator`` --> ``Global Styles`` --> ``Current line background`` to the same color it is already set (which is the installation default). but, TBH, I usually just close and restart NPP, cause then the line background is fine again.  Nevertheless, this is a bit annoying ...

**Comment by pnedev** [comment]
Hello @MagpieFourtyTwo ,

For fixing the compatibility issue with NppTextFX please manually update the ComparePlus to the current dev version (I haven't made a new release yet since there are a number of other improvements I need to do first) - you can get it from the `master` branch or get directly the new plugin DLL from here: **[64-bit](https://ci.appveyor.com/api/buildjobs/p53jdce9pnbw5kjd/artifacts/ComparePlus.dll)** or **[32-bit](https://ci.appveyor.com/api/buildjobs/1v1ypib71mysnth9/artifacts/ComparePlus.dll)**. If you need help with the manual change of the DLL please write back and I will assist you.

About the caret line background please check these workaround instructions for the CSVLint plugin: https://github.com/pnedev/comparePlus/issues/360#issuecomment-1642039025.

If you have further question just write back or if your problems are fixed please close this thread.
Thanks for the debug info.

BR

**Comment by MagpieFourtyTwo** [comment]
ComparePlus dev version: Works like a charm!

WRT [#360 comment](https://github.com/pnedev/comparePlus/issues/360#issuecomment-1642039025): Worked too (although had to make both changes).

THX a lot, three times: For double help and esp. the immediate reply! ;)
