### ISSUE TITLE
"Ignore Spaces" problem with "_" character?

### ISSUE THREAD

**Issue by Serpens66** [pnedev/comparePlus#374]
Thank you very much for this Plugin :)

Not sure if it is intended, but when I choose the option to "ignore Spaces" when comparing, it claims that these lines matches:
`     if a and  b and _b then`
vs:
`        if a and b and_b then`
The problem is that "and _b" vs "and_b" is something totally different.
( want to ignore spaces at line beginning and also spaces after ",")

This only happens if I use the underscore "_" at front of a variable name. Is this intended? Should I simply not use underscores like this? Or is this a bug?

**edit:**
I just noticed the problem also happens for
`and not`
vs
`andnot`
which is also not the same =/

**Comment by pnedev** [comment]
It is a known issue and for your use case is definitely not the proper behavior (in other cases it might be useful).
This issue is already fixed and will be in the next plugin release (whenever that will be ready) but meanwhile you could use the development builds: **[Win 32-bit](https://ci.appveyor.com/api/buildjobs/0asbkf55a6nqf112/artifacts/ComparePlus.dll)** / **[Win 64-bit](https://ci.appveyor.com/api/buildjobs/fte8jddwcmmcxv7g/artifacts/ComparePlus.dll)**
Use the new option _Ignore Changed Spaces_ instead of the _Ignore All Spaces_ one (that is practically the same as what you described - ignoring every space).

BR
