### ISSUE TITLE
Cannot download ComparePlus plugin ZIP from my work laptop (connected via VPN)

### ISSUE THREAD

**Issue by tarekahf** [pnedev/comparePlus#380]
I usually install NPP Plugins manually and it works fine. This time with ComparePlus, I cannot even download the ZIP file. I then downloaded it from my mobile and emailed it to my work and Gmail emails. Even Gmail rejected it due to security issues. Please review and correct the issue.

Then, I tried to update the exiting Compare, and the GitHub link of the Compare plugin is taking me to ComparePlus plugin so I suppose that ComparePlus is the next version of Compare.

I appreciate your feedback.

Tarek

**Comment by pnedev** [comment]
Hello,

ComparePlus also hosts the latest available Compare release and yes, I stopped supporting Compare and made ComparePlus as its more advanced successor.

All releases are hosted here on GitHub and are automatically built and prepared by AppVeyor so its very unlikely those to be infected. There hasn't been a new release since at least half an year so the current releases had been around for some time and had been downloaded and installed a lot without any issues.

This probably means that either GitHub have had some issues (being temporarily down - highly unlikely) when you tried downloading or you have some rules that prevent you from downloading from it.

You can try again visiting the Compare/ComparePlus **[Releases](https://github.com/pnedev/comparePlus/releases)** and try downloading the zip of the release you like from there, just make sure it matches your Notepad++ variant - either 32 or 64 bit. If you have problems with the manual install you could carefully read the README down **[here](https://github.com/pnedev/comparePlus)**.

If you have further questions or need further assistance you could write again in this thread.

BR

**Comment by tarekahf** [comment]
8 downloaded it using my mobile and emailed the zip file to my Gmail and it was rejected by Gmail. There is a problem. Please verify.

**Comment by pnedev** [comment]
The problem is not the plugin archive but GMail opening the attachment and seeing inside a DLL file. It comsiders this dangerous and a potential thread and rejects the mail.
Try doing the same with any other plugin zip file and you should get the same result.

Instead of e-mailing the zip via GMail you could connect your phone with a data cable to the PC and download it directly from the phone. This might be forbidden in your organization though and if that's the case I don't know what else you could do.
But anyway - it is not a problem with the plugin or the archive but with the data policies on your side (your PC and GMail).

**Comment by tarekahf** [comment]
I see.

Why I was able to download many other plugins manually but ONLY this one it was blocked from my wrk lptp? I get error from the browser that it's not found or something like that. Maybe if you can provide alternate download location with zip file with a PWD it may work.

**Comment by pnedev** [comment]
What version of ComparePlus plugin do you want, 1.1.0 64-bit ?

**Comment by tarekahf** [comment]
The latest 32 bit. Just please make sure it's clean. Did you scan it?

**Comment by pnedev** [comment]
[ComparePlus_cp_1.1.0_Win32.zip](https://github.com/pnedev/comparePlus/files/14320358/ComparePlus_cp_1.1.0_Win32.zip)
Password is "Tarek".
I didn't detect any malware.

**Comment by tarekahf** [comment]
I'm still getting rejection message from Gmail with the new file. From the other side, I'll check later.

Below is part of rejection message I saw after sending to Gmail:

host gmail-smtp-in.l.google.com[142.251.16.26] said:
    552-5.7.0 This message was blocked because its content presents a potential
    552-5.7.0 security issue. To review our message content and attachment
    content 552-5.7.0 guidelines, go to 552 5.7.0
    https://support.google.com/mail/?p=BlockedMessage
  

I'm honestly surprised others didn't report this issue. I reported this problem to Corp. Support and requested escalation.

**Comment by pnedev** [comment]
This issue is due to the mailing system - perhaps either Gmail doesn't allow password protected archives as attachment or your receiving mailbox does not allow them. Others don't use such workaround ways to get the plugin.

Last thing you could try is to rename the downloaded zip to `something.wav` or `something.dat` for example and try sending it again. You will rename it back to .zip if you manage to receive it successfully.
I cannot help you any further, good luck.

**Comment by tarekahf** [comment]
Thank you. I received the file from my other email. I'll ask the security team to check it. I can't thank you enough.
